---
- hosts: localhost
  become: yes
  vars:
    ssh_key_source: "./.ssh/personal-github"
    localhost_ssh_key_destination: "{{ lookup('env','HOME') }}/.ssh/personal-github"
    personal_directory: "{{ lookup('env', 'HOME') }}/personal"

  pre_tasks:
    - name: Update Apt Package Manager
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - install
        - core

  tasks:
    - include_tasks: tasks/ssh.yml
    - include_tasks: tasks/core-utilities.yml
    - include_tasks: tasks/nodejs.yml
    #- include_tasks: tasks/alacritty.yml    Not Working by now!
    - include_tasks: tasks/zsh.yml

    # - include_tasks: tasks/languages/
    # - include_tasks: tasks/languages/
    # - include_tasks: tasks/languages/
    # - include_tasks: tasks/languages/
    # - include_tasks: tasks/languages/
    # - include: tasks/languages.yml
    # - include: tasks/zsh-setup.yml

