---
- hosts: localhost
  become: true
  vars:
    ssh_key_source: "./.ssh/personal-github"
    localhost_ssh_key_destination: "{{ lookup('env','HOME') }}/.ssh/personal-github"
    personal_gh_directory: "{{ lookup('env', 'HOME') }}/personal/github"
    personal_gl_directory: "{{ lookup('env', 'HOME') }}/personal/gitlab"
    work_fitcrew_directory: "{{ lookup('env', 'HOME')}}/work/fitcrew/gitlab"

  pre_tasks:
    - name: Update Apt Package Manager
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - install
        - core

  tasks:
    - include_tasks: tasks/filesystem.yml
    - include_tasks: tasks/ssh.yml
    - include_tasks: tasks/core-utilities.yml
    - include_tasks: tasks/nodejs.yml
    - include_tasks: tasks/zsh.yml
    - include_tasks: tasks/neovim.yml
    # - include_tasks: tasks/alacritty-terminal.yml    #Not Working by now!
    # - include_tasks: tasks/personal.yml    Not working by now!
    - include_tasks: tasks/languages/php.yml   # Don't forget to add intelephense!
    - include_tasks: tasks/languages/typescript.yml
    - include_tasks: tasks/languages/clanguages.yml  # look for debuggers, linters etc.
    - include_tasks: tasks/languages/python.yml
    - include_tasks: tasks/languages/java.yml  # Plant
    - include_tasks: tasks/languages/go.yml
    #- include_tasks: tasks/nordpass.yml  Not working by now!
    #- include_tasks: tasks/google-chrome.yml Not working by now!

    # - include_tasks: tasks/languages/
    # - include_tasks: tasks/languages/
    # - include_tasks: tasks/languages/
    # - include_tasks: tasks/languages/
    # - include_tasks: tasks/languages/
    # - include: tasks/languages.yml
    # - include: tasks/zsh-setup.yml

