- hosts: localhost
  vars:
    # ssh stuff
  pre_tasks:
  - name: Update Apt Package Manager
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
      - core
    tasks:
      - include: tasks/ssh.yml
      - include: tasks/core-utilities.yml
      - include: tasks/languages.yml
      - include: tasks/zsh-setup.yml

