---
- hosts: localhost
  become: true
  vars:
    ssh_key_source: "./.ssh/personal-github"
    localhost_ssh_key_destination: "{{ lookup('env', 'HOME') }}/.ssh/personal-github"
    intelephense_licence_source: "./intelephense/licence.txt"
    intelephense_licence_destination: "{{ lookup('env', 'HOME') }}/intelephense"
    font_source: "./.fonts"
    font_destination: "{{ lookup('env', 'HOME') }}/.fonts"
    personal_gh_directory: "{{ lookup('env', 'HOME') }}/personal/github"
    personal_gl_directory: "{{ lookup('env', 'HOME') }}/personal/gitlab"
    work_fitcrew_directory: "{{ lookup('env', 'HOME')}}/work/fitcrew/gitlab"

  pre_tasks:
    - name: Update APT Package Manager
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - install
        - core

  tasks:
    - include_tasks: tasks/filesystem.yml
    - include_tasks: tasks/ssh.yml
    - include_tasks: tasks/core-utilities.yml
    - include_tasks: tasks/eza.yml
    - include_tasks: tasks/personal.yml
    # - include_tasks: tasks/git.yml
    # - include_tasks: tasks/tmux.yml
    # - include_tasks: tasks/languages/php.yml
    # - include_tasks: tasks/languages/clanguages.yml
    # - include_tasks: tasks/languages/python.yml
    # - include_tasks: tasks/languages/java.yml
    # - include_tasks: tasks/languages/go.yml
    # # - include_tasks: tasks/languages/rust.yml   # A newer version is provided by the Rust installer.
    # - include_tasks: tasks/i3wm.yml
    # - include_tasks: tasks/neovim.yml
    # - include_tasks: tasks/nodejs.yml
    # - include_tasks: tasks/alacritty-terminal.yml
    # - include_tasks: tasks/languages/typescript.yml
    # - include_tasks: tasks/google-chrome.yml
    # - include_tasks: tasks/docker.yml
    # - include_tasks: tasks/zsh.yml

