- name: Download Alacritty Terminal Emulator
  become: true
  command: add-apt-repository ppa:aslatter/ppa
  tags:
    - install
    - alacritty

- name: Update Package List
  become: true
  apt:
    update_cache: yes
  tags:
    - install
    - alacritty

- name: Install Alacritty Terminal Emulator
  become: true
  command: apt-get install -y alacritty
  # apt:
  #   name: alacritty
  #   state: present
  tags:
    - install
    - alacritty

