- name: Link Own Alacritty Configuration File
  become: true
  command: ln -s "{{ lookup('env', 'HOME') }}/dotfiles/alacritty/.alacritty.toml-linux" "{{ lookup('env', 'HOME') }}/.alacritty.toml"
  tags:
    - install
    - tools
    - alacritty


# - name: Install Alacritty
#   become: true
#   apt:
#     name: alacritty
#   tags:
#     - install
#     - tools
#     - alacritty


- name: Install Alacritty
  become: true
  # environment:
  #   PATH: "{{ ansible_env.PATH }}:~/.cargo/env"
  command: cargo install alacritty
  tags:
    - install
    - tools
    - alacritty



# - name: Clone Alacritty Repository
#   ansible.builtin.git:
#     repo: "https://github.com/alacritty/alacritty.git"
#     dest: "{{ lookup('env', 'HOME') }}/alacritty"
#   tags:
#     - install
#     - tools
#     - alacritty

# - name: lfajlfa
#   shell: "cd {{ lookup('env', 'HOME') }}/alacritty && rustup override set stable && rustup update stable"
#   tags:
#     - install
#     - tools
#     - alacritty

# - name: Build Alacritty
#   become: true
#   shell: "cd {{ lookup('env', 'HOME') }}/alacritty && cargo build --release"
#   tags:
#     - install
#     - tools
#     - alacritty
