- name: Download Alacritty Terminal Emulator
  become: true
  apt_repository:
    repo: 'ppa:aslatter/ppa'
    state: present
  tags:
    - install
    - alacritty

- name: Update Package List
  become: true
  apt:
    update_cache: yes
  tags:
    - install
    - alacritty

- name: Install Alacritty Terminal Emulator
  become: true
  command: apt-get install -y alacritty
  # apt:
  #   name: alacritty
  #   state: present
  tags:
    - install
    - alacritty

