- name: Core Utilities - Set 1 - Install build-essential, cmake, pkg-config, pthread, apt-transport-https, ca-certificates, virtualenv
  become: true
  apt:
    name: ["build-essential", "cmake", "pkg-config", "libpthread-stubs0-dev", "apt-transport-https", "ca-certificates", "virtualenv"]
  tags:
    - install
    - neovim
    - core

- name: Core Utilities - Set 2 - Install lua, unzip, libtool, libtool-bin, gettext, software-properties-common, gnupg2
  become: true
  apt:
    name: ["lua5.3", "unzip", "libtool", "libtool-bin", "gettext", "software-properties-common", "gnupg2"]
  tags:
    - install
    - neovim
    - core

- name: Core Utilities - Set 3 - Install libfreetype6-dev, libfontconfig1-dev, libxcb-xfixes0-dev, libxkbcommon-dev
  become: true
  apt:
    name: ["libfreetype6-dev", "libfontconfig1-dev", "libxcb-xfixes0-dev", "libxkbcommon-dev"]
  tags:
    - install
    - neovim
    - core

- name: Core Utilities - Set 4 - Install curl, wget, bat, htop, lsof, ccache, ninja-build, graphviz, ripgrep, fzf
  become: true
  apt:
    name: ["curl", "wget", "bat", "htop", "lsof", "ccache", "ninja-build", "graphviz", "ripgrep", "fzf"]
  tags:
    - install
    - neovim
    - core

- name: Core Utilities - Set 5 - Install ssh, i3wm, tmux, dconf-editor, nvidia-settings, pavucontrol, moreutils, snap, PlantUML
  become: true
  apt:
    name: ["ssh", "i3", "tmux", "dconf-editor", "nvidia-settings", "pavucontrol", "moreutils", "snapd", "plantuml"]
  tags:
    - install
    - neovim
    - core

- name: Core Utilities - Set 6 - Install download deno
  become: true
  command: sh -c "curl -Lo 'deno.zip' 'https://github.com/denoland/deno/releases/latest/download/deno-x86_64-unknown-linux-gnu.zip'"
  tags:
    - install
    - neovim
    - core

- name: Core Utilities - Set 7 - Install unzip and install deno
  become: true
  command: sh -c "sudo unzip -d /usr/local/bin deno.zip"
  tags:
    - install
    - neovim
    - core

- name: Core Utilities - Set 8 - copy Meslo Nerd Font
  owner: manny
  group: manny
  copy:
    src: "{{ font_source }}"
    dest: "{{ font_destination }}"
    mode: '0755'
  tags:
    - install
    - neovim
    - core

- name: Core Utilities - Set 9 - rebuild font cache
  become: true
  command: fc-cache -fv
  tags:
    - install
    - neovim
    - core
