- name: Install Core Utilities Set 1 (build-essential, cmake, pkg-config, pthread)
  become: true
  apt:
    name: ["build-essential", "cmake", "pkg-config", "libpthread-stubs0-dev"]
  tags:
    - install
    - neovim
    - core

- name: Install Core Utilities Set 2 (lua, unzip, libtool, libtool-bin, gettext, software-properties-common)
  become: true
  apt:
    name: ["lua5.3", "unzip", "libtool", "libtool-bin", "gettext", "software-properties-common"]
  tags:
    - install
    - neovim
    - core

- name: Install Core Utilities Set 3 (curl, wget, bat, htop, lsof, ccache, ninja-build, graphviz, ripgrep, fzf)
  become: true
  apt:
    name: ["curl", "wget", "bat", "htop", "lsof", "ccache", "ninja-build", "graphviz", "ripgrep", "fzf"]
  tags:
    - install
    - neovim
    - core

- name: Install Core Utilities Set 4 (ssh, git, i3wm, tmux, dconf-editor, nvidia-settings, pavucontrol, moreutils)
  become: true
  apt:
    name: ["ssh", "git", "i3", "tmux", "dconf-editor", "nvidia-settings", "pavucontrol", "moreutils"]
  tags:
    - install
    - neovim
    - core

- name: Install Core Utilities Set 5 (download deno)
  become: true
  command: sh -c "curl -Lo 'deno.zip' 'https://github.com/denoland/deno/releases/latest/download/deno-x86_64-unknown-linux-gnu.zip'"
  tags:
    - install
    - neovim
    - core

- name: Install Core Utilities Set 6 (unzip and install deno)
  become: true
  command: sh -c "sudo unzip -d /usr/local/bin deno.zip"
  tags:
    - install
    - neovim
    - core
