- name: Docker - Uninstall maybe existing Docker environment
  become: true
  shell: "for pkg in docker.io docker-doc docker-compose docker-compose-v2 podman-docker containerd runc; do sudo apt-get remove $pkg; done"
  tags:
    - install
    - tools
    - docker

- name: Docker - Update APT Packages
  become: true
  apt:
    force_apt_get: true
    update_cache: true
    state: present
  tags:
    - install
    - tools
    - docker

- name: Docker - Add Docker GPG APT Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags:
    - install
    - tools
    - docker

- name: Docker - Create Directory for Docker GPG Key
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  tags:
    - install
    - tools
    - docker

- name: Docker - Download Docker GPG Key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
  tags:
    - install
    - tools
    - docker

- name: Docker - Set Permissions for Docker GPG Key
  file:
    path: /etc/apt/keyrings/docker.asc
    mode: '0644'
  tags:
    - install
    - tools
    - docker

- name: Docker - Add Docker Repository to APT Resources
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu jammy stable
    state: present
  tags:
    - install
    - tools
    - docker

- name: Docker - Update APT Packages
  become: true
  apt:
    force_apt_get: true
    update_cache: true
    state: present
  tags:
    - install
    - tools
    - docker

- name: Docker - Install Docker Packages
  apt:
    name: ["docker-ce", "docker-ce-cli", "containerd.io", "docker-buildx-plugin", "docker-compose-plugin"]
    state: present
  tags:
    - install
    - tools
    - docker

- name: Docker - Install Docker Module for Python
  pip:
    name: docker
  tags:
    - install
    - tools
    - docker

- name: Docker - Update APT Packages
  become: true
  apt:
    force_apt_get: true
    update_cache: true
    state: present
  tags:
    - install
    - tools
    - docker

- name: Docker - Create Docker Group
  group:
    name: docker
    state: present
  tags:
    - install
    - tools
    - docker

- name: Docker - Add User to Docker Group
  user:
    name: manny
    groups: docker
    append: yes
  tags:
    - install
    - tools
    - docker

- name: Docker - Ensure User is added to Docker Group
  command: id -nG manny
  register: user_groups
  tags:
    - install
    - tools
    - docker

