- name: eza - Create directories
  become: true
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - "/etc/apt/keyrings"
    - "/etc/apt/sources.list.d"
  tags:
    - installation
    - tools
    - eza

- name: eza - Download GPG key
  become: true
  get_url:
    url: https://raw.githubusercontent.com/eza-community/eza/main/deb.asc
    dest: /etc/apt/keyrings/gierens.gpg.tmp
  tags:
    - installation
    - tools
    - eza

- name: eza - Install GPG key
  become: true
  command: gpg --dearmor -o /etc/apt/keyrings/gierens.gpg /etc/apt/keyrings/gierens.gpg.tmp
  args:
    creates: /etc/apt/keyrings/gierens.gpg
  tags:
    - installation
    - tools
    - eza
 
- name: eza - Create gierens.list file
  become: true
  file:
    path: /etc/apt/sources.list.d/gierens.list
    state: touch
    mode: '0644'
  tags:
    - installation
    - tools
    - eza

- name: eza - Add eza APT repository
  become: true
  lineinfile:
    path: /etc/apt/sources.list.d/gierens.list
    line: 'deb [signed-by=/etc/apt/keyrings/gierens.gpg] http://deb.gierens.de stable main'
  tags:
    - installation
    - tools
    - eza

- name: eza - Set permissions for GPG key and repository file
  become: true
  file:
    path: "{{ item }}"
    mode: '0644'
  with_items:
    - "/etc/apt/keyrings/gierens.gpg"
    - "/etc/apt/sources.list.d/gierens.list"
  tags:
    - installation
    - tools
    - eza

- name: eza - Update APT cache
  become: true
  apt:
    update_cache: yes
  tags:
    - installation
    - tools
    - eza

- name: eza - Install eza package
  become: true
  apt:
    name: eza
    state: present
  tags:
    - installation
    - tools
    - eza
