- name: File System - Add user to sudo Group
  become: true
  user:
    name: "{{ username }}"
    groups: sudo
    append: yes
  tags:
    - install
    - filesystem

- name: Create File System
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0755'
  with_items:
    - "{{ lookup('env', 'HOME') }}/dotfiles"
    - "{{ lookup('env', 'HOME') }}/.config"
    - "{{ lookup('env', 'HOME') }}/intelephense"
    - "{{ lookup('env', 'HOME') }}/personal"
    - "{{ lookup('env', 'HOME') }}/personal/github"
    - "{{ lookup('env', 'HOME') }}/personal/gitlab"
    - "{{ lookup('env', 'HOME') }}/work"
    - "{{ lookup('env', 'HOME') }}/work/vds"
    - "{{ lookup('env', 'HOME') }}/work/vds/github"
    - "{{ lookup('env', 'HOME') }}/work/fitcrew"
    - "{{ lookup('env', 'HOME') }}/work/fitcrew/gitlab"
  tags:
    - install
    - filesystem
