- name: File System - Add user to sudo Group
  become: true
  user:
    name: "{{ username }}"
    groups: sudo
    append: yes
  tags:
    - install
    - filesystem

- name: Create File System
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0755'
  with_items:
    - "{{ lookup('env', 'HOME') }}/dotfiles"
    - "{{ lookup('env', 'HOME') }}/.config"
    - "{{ lookup('env', 'HOME') }}/intelephense"
    - "{{ lookup('env', 'HOME') }}/personal"
    - "{{ lookup('env', 'HOME') }}/personal/github"
    - "{{ lookup('env', 'HOME') }}/personal/gitlab"
    - "{{ lookup('env', 'HOME') }}/work"
    - "{{ lookup('env', 'HOME') }}/work/vds"
    - "{{ lookup('env', 'HOME') }}/work/vds/github"
    - "{{ lookup('env', 'HOME') }}/work/fitcrew"
    - "{{ lookup('env', 'HOME') }}/work/fitcrew/gitlab"
  tags:
    - install
    - filesystem

# - name: File System - Create ~/.config Directory
#   ansible.builtin.file:
#     path: "{{ lookup('env', 'HOME') }}/.config"
#     state: directory
#     owner: "{{ username }}"
#     group: "{{ username }}"
#     mode: '0755'
#   tags:
#     - install
#     - filesystem

# #- name: File System - Create ~/.fonts Directory
#   #become: true
#  # ansible.builtin.file:
#    # path: "{{ lookup('env', 'HOME') }}/.fonts"
#   #  state: directory
#   #  owner: "{{ username }}"
#    # group: "{{ username }}"  # Replace with your group (you can check with 'groups' command)
#    # mode: '0755'
#   #tags:
#   #  - install
#   #  - filesystem

# - name: File System - Create ~/intelephense Directory
#   ansible.builtin.file:
#     path: "{{ lookup('env', 'HOME') }}/intelephense"
#     state: directory
#     owner: "{{ username }}"
#     group: "{{ username }}"
#     mode: '0755'
#   tags:
#     - install
#     - filesystem

# - name: File System - Create ~/personal Directory
#   ansible.builtin.file:
#     path: "{{ lookup('env', 'HOME') }}/personal"
#     state: directory
#     owner: "{{ username }}"
#     group: "{{ username }}"
#     mode: '0755'
#   tags:
#     - install
#     - filesystem

# - name: File System - Create ~/personal/github Directory
#   ansible.builtin.file:
#     path: "{{ lookup('env', 'HOME') }}/personal/github"
#     state: directory
#     owner: "{{ username }}"
#     group: "{{ username }}"
#     mode: '0755'
#   tags:
#     - install
#     - filesystem

# - name: File System - Create ~/personal/gitlab Directory
#   ansible.builtin.file:
#     path: "{{ lookup('env', 'HOME') }}/personal/gitlab"
#     state: directory
#     owner: "{{ username }}"
#     group: "{{ username }}"
#     mode: '0755'
#   tags:
#     - install
#     - filesystem

# - name: File System - Create ~/work Directory
#   ansible.builtin.file:
#     path: "{{ lookup('env', 'HOME') }}/work"
#     state: directory
#     owner: "{{ username }}"
#     group: "{{ username }}"
#     mode: '0755'
#   tags:
#     - install
#     - filesystem

# - name: File System - Create ~/work/vds Directory
#   ansible.builtin.file:
#     path: "{{ lookup('env', 'HOME') }}/work/vds"
#     state: directory
#     owner: "{{ username }}"
#     group: "{{ username }}"
#     mode: '0755'
#   tags:
#     - install
#     - filesystem

# - name: File System - Create ~/work/vds/github Directory
#   ansible.builtin.file:
#     path: "{{ lookup('env', 'HOME') }}/work/vds/github"
#     state: directory
#     owner: "{{ username }}"
#     group: "{{ username }}"
#     mode: '0755'
#   tags:
#     - install
#     - filesystem

# - name: File System - Create ~/work/fitcrew Directory
#   ansible.builtin.file:
#     path: "{{ lookup('env', 'HOME') }}/work/fitcrew"
#     state: directory
#     owner: "{{ username }}"
#     group: "{{ username }}"
#     mode: '0755'
#   tags:
#     - install
#     - filesystem

# - name: File System - Create ~/work/fitcrew/gitlab Directory
#   ansible.builtin.file:
#     path: "{{ lookup('env', 'HOME') }}/work/fitcrew/gitlab"
#     state: directory
#     owner: "{{ username }}"
#     group: "{{ username }}"
#     mode: '0755'
#   tags:
#     - install
#     - filesystem
