- name: File System - Add manny to sudo Group
  become: true
  user:
    name: manny
    groups: sudo
    append: yes
  tags:
    - install
    - filesystem

- name: File System - Create ~/dotfiles Directory
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/dotfiles"
    state: directory
    owner: manny
    group: manny
    mode: '0755'
  tags:
    - install
    - filesystem

- name: File System - Create ~/.config Directory
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.config"
    state: directory
    owner: manny
    group: manny
    mode: '0755'
  tags:
    - install
    - filesystem

#- name: File System - Create ~/.fonts Directory
  #become: true
 # ansible.builtin.file:
   # path: "{{ lookup('env', 'HOME') }}/.fonts"
  #  state: directory
  #  owner: manny
   # group: manny  # Replace with your group (you can check with 'groups' command)
   # mode: '0755'
  #tags:
  #  - install
  #  - filesystem

- name: File System - Create ~/intelephense Directory
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/intelephense"
    state: directory
    owner: manny
    group: manny
    mode: '0755'
  tags:
    - install
    - filesystem

- name: File System - Create ~/personal Directory
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/personal"
    state: directory
    owner: manny
    group: manny
    mode: '0755'
  tags:
    - install
    - filesystem

- name: File System - Create ~/personal/github Directory
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/personal/github"
    state: directory
    owner: manny
    group: manny
    mode: '0755'
  tags:
    - install
    - filesystem

- name: File System - Create ~/personal/gitlab Directory
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/personal/gitlab"
    state: directory
    owner: manny
    group: manny
    mode: '0755'
  tags:
    - install
    - filesystem

- name: File System - Create ~/work Directory
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/work"
    state: directory
    owner: manny
    group: manny
    mode: '0755'
  tags:
    - install
    - filesystem

- name: File System - Create ~/work/vds Directory
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/work/vds"
    state: directory
    owner: manny
    group: manny
    mode: '0755'
  tags:
    - install
    - filesystem

- name: File System - Create ~/work/vds/github Directory
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/work/vds/github"
    state: directory
    owner: manny
    group: manny
    mode: '0755'
  tags:
    - install
    - filesystem

- name: File System - Create ~/work/fitcrew Directory
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/work/fitcrew"
    state: directory
    owner: manny
    group: manny
    mode: '0755'
  tags:
    - install
    - filesystem

- name: File System - Create ~/work/fitcrew/gitlab Directory
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/work/fitcrew/gitlab"
    state: directory
    owner: manny
    group: manny
    mode: '0755'
  tags:
    - install
    - filesystem
