- name: Git - Link Global Git Configuration File
  become: true
  become_user: "{{ username }}"
  command: "{{ item }}"
  with_items:
    - ln -s "{{ lookup('env', 'HOME') }}/dotfiles/git/account-config/global" "{{ lookup('env', 'HOME') }}/.gitconfig"
    - ln -s "{{ lookup('env', 'HOME') }}/dotfiles/git/account-config/personal/github" "{{ personal_gh_directory }}/.gitconfig"
    - ln -s "{{ lookup('env', 'HOME') }}/dotfiles/git/account-config/personal/gitlab" "{{ personal_gl_directory }}/.gitconfig"
    - ln -s "{{ lookup('env', 'HOME') }}/dotfiles/git/account-config/personal/gitlab" "{{ work_fitcrew_directory }}/.gitconfig"
    - ln -s "{{ lookup('env', 'HOME') }}/dotfiles/git/account-config/work/github" "{{ lookup('env', 'HOME') }}/work/vds/github/.gitconfig"
  tags:
    - install
    - core
    - git

