- name: Link Global Git Configuration File
  become: true
  command: ln -s "{{ lookup('env', 'HOME') }}/dotfiles/git/account-config/global" "{{ lookup('env', 'HOME') }}/.gitconfig"
  tags:
    - install
    - core
    - git

- name: Link Personal GitHub Configuration File
  become: true
  command: ln -s "{{ lookup('env', 'HOME') }}/dotfiles/git/account-config/personal/github" "{{ personal_gh_directory }}/.gitconfig"
  tags:
    - install
    - core
    - git

- name: Link Personal GitLab Configuration File
  become: true
  command: ln -s "{{ lookup('env', 'HOME') }}/dotfiles/git/account-config/personal/gitlab" "{{ personal_gl_directory }}/.gitconfig"
  tags:
    - install
    - core
    - git

- name: Link Work fitcrew GitLab Configuration File
  become: true
  command: ln -s "{{ lookup('env', 'HOME') }}/dotfiles/git/account-config/personal/gitlab" "{{ work_fitcrew_directory }}/.gitconfig"
  tags:
    - install
    - core
    - git

- name: Link Work VdS GitHub Configuration File
  become: true
  command: ln -s "{{ lookup('env', 'HOME') }}/dotfiles/git/account-config/work/github" "{{ lookup('env', 'HOME') }}/work/vds/github/.gitconfig"
  tags:
    - install
    - core
    - git

