- name: Google Chrome - Download Google Chrome .deb package
  become: true
  get_url:
    url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    dest: /tmp/google-chrome-stable_current_amd64.deb
  tags:
    - install
    - tools
    - chrome

- name: Google Chrome - Install Google Chrome
  apt:
    deb: /tmp/google-chrome-stable_current_amd64.deb
  tags:
    - install
    - tools
    - chrome

