- name: Clone Neovim Repository
  ansible.builtin.git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: "{{ lookup('env', 'HOME') }}/neovim"
    version: stable
  tags:
    - install
    - tools
    - neovim

- name: Build Neovim
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && make CMAKE_BUILD_TYPE=RelWithDebInfo"
  tags:
    - install
    - tools
    - neovim

- name: Install Neovim
  become: true
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && make install"
  tags:
    - install
    - tools
    - neovim

- name: Link Neovim Configuration to ~/.config
  become: true
  command: ln -s "{{ lookup('env', 'HOME') }}/dotfiles/nvim" "{{ lookup('env', 'HOME') }}/.config/nvim"
  tags:
    - install
    - tools
    - neovim
