# - name: Install NordPass
#   become: true
#   ansible.builtin.snap:
#     name: nordpass
#     state: present
#   tags:
#     - install
#     - tools
#     - nordpass

- name: Download NordPass
  become: true
  command: "wget https://snapcraft.io/nordpass"
  tags:
    - install
    - tools
    - nordpass

- name: Install NordPass
  become: true
  command: snap install nordpass
  tags:
    - install
    - tools
    - nordpass
