- name: Repositories - Clone dotfiles Repository
  ansible.builtin.git:
    repo: "https://github.com/MannyFay/dotfiles.git"
    dest: "{{ lookup('env', 'HOME') }}/dotfiles"
  tags:
    - install
    - projects

- name: Repositories - Set ownership of dotfiles Repository
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/dotfiles"
    owner: manny
    group: manny
    recurse: true
  become: true

- name: Repositories - Clone mannydark.nvim Repository
  become: true
  become_user: manny
  ansible.builtin.git:
    repo: "https://github.com/MannyFay/mannydark.nvim.git"
    dest: "{{ personal_gh_directory }}/mannydark.nvim"
  tags:
    - install
    - projects

- name: Repositories - Set ownership of mannydark.nvim Repository
  ansible.builtin.file:
    path: "{{ personal_gh_directory }}/mannydark.nvim"
    owner: manny
    group: manny
    recurse: true
  become: true

- name: Repositories - Clone set-up-web-dev-macos Repository
  become: true
  become_user: manny
  ansible.builtin.git:
    repo: "https://github.com/MannyFay/set-up-web-dev-macos.git"
    dest: "{{ personal_gh_directory }}/set-up-web-dev-macos"
  tags:
    - install
    - projects

- name: Repositories - Set ownership of set-up-web-dev-macos Repository
  ansible.builtin.file:
    path: "{{ personal_gh_directory }}/set-up-web-dev-macos"
    owner: manny
    group: manny
    recurse: true
  become: true

- name: Repositories - Clone short-cuts-and-commands Repository
  become: true
  become_user: manny
  ansible.builtin.git:
    repo: "https://github.com/MannyFay/short-cuts-and-commands.git"
    dest: "{{ personal_gh_directory }}/short-cuts-and-commands"
  tags:
    - install
    - projects

- name: Repositories - Set ownership of short-cuts-and-commands Repository
  ansible.builtin.file:
    path: "{{ personal_gh_directory }}/short-cuts-and-commands"
    owner: manny
    group: manny
    recurse: true
  become: true

- name: Repositories - Clone start-to-code Repository
  become: true
  become_user: manny
  ansible.builtin.git:
    repo: "https://github.com/MannyFay/start-to-code.git"
    dest: "{{ personal_gh_directory }}/start-to-code"
  tags:
    - install
    - projects

- name: Repositories - Set ownership of start-to-code Repository
  ansible.builtin.file:
    path: "{{ personal_gh_directory }}/start-to-code"
    owner: manny
    group: manny
    recurse: true
  become: true
