- name: Clone Repositories
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
  with_items:
    - { repo: "https://github.com/MannyFay/dotfiles.git", dest: "{{ lookup('env', 'HOME') }}/dotfiles" }
    - { repo: "https://github.com/MannyFay/mannydark.nvim.git", dest: "{{ personal_gh_directory }}/mannydark.nvim" }
    - { repo: "https://github.com/MannyFay/set-up-web-dev-macos.git", dest: "{{ personal_gh_directory }}/set-up-web-dev-macos" }
    - { repo: "https://github.com/MannyFay/short-cuts-and-commands.git", dest: "{{ personal_gh_directory }}/short-cuts-and-commands" }
    - { repo: "https://github.com/MannyFay/start-to-code.git", dest: "{{ personal_gh_directory }}/start-to-code" }
  tags:
    - install
    - projects

- name: Set ownership of Repositories
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    recurse: true
  become: true
  with_items:
    - { path: "{{ lookup('env', 'HOME') }}/dotfiles", owner: "{{ username }}", group: "{{ username }}" }
    - { path: "{{ personal_gh_directory }}/mannydark.nvim", owner: "{{ username }}", group: "{{ username }}" }
    - { path: "{{ personal_gh_directory }}/set-up-web-dev-macos", owner: "{{ username }}", group: "{{ username }}" }
    - { path: "{{ personal_gh_directory }}/short-cuts-and-commands", owner: "{{ username }}", group: "{{ username }}" }
    - { path: "{{ personal_gh_directory }}/start-to-code", owner: "{{ username }}", group: "{{ username }}" }
  tags:
    - install
    - projects
 
