---
- name: Install Polypane Browser
  tasks:
    - name: Download Polypane Debian Package
      get_url:
        url: https://github.com/firstversionist/polypane/releases/download/v17.0.0/polypane_17.0.0_amd64.deb
        dest: /tmp/polypane_17.0.0_amd64.deb

    - name: Install Polypane using dpkg
      become: yes
      command: dpkg -i /tmp/polypane_17.0.0_amd64.deb
