- name: Ensure ~/.ssh directory exists
  file:
    dest: "{{ localhost_ssh_key_destination | dirname }}"
    mode: 0700
    state: directory
  tags:
    - dotfiles
    - install
    - ssh

- name: Install private SSH key
  copy:
    src: "{{ ssh_key_source }}"
    dest: "{{ localhost_ssh_key_destination }}"
    mode: 0600
  tags:
    - dotfiles
    - install
    - ssh

- name: Install public SSH key
  copy:
    src: "{{ ssh_key_source }}.pub"
    dest: "{{ localhost_ssh_key_destination }}.pub"
    mode: 0644
  tags:
    - dotfiles
    - install
    - ssh

- name: Took authorized key from file and set it
  authorized_key:
    user: "{{ lookup('env', 'USER') }}"
    state: present
    key: "{{ lookup('env', 'HOME') }}/.ssh/personal-github"
  with_fileglob:
    - "{{ lookup('env', 'HOME') }}/.ssh/personal-github"
