- name: Install ZSH
  become: true
  apt:
    name: zsh
  tags:
    - install
    - zsh

- name: Change Shell to ZSH
  become: true
  shell: chsh -s $(which zsh)
  tags:
    - install
    - zsh

- name: Install Oh-My-ZSH
  become: true
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  tags:
    - install
    - zsh

- name: Install ZSH-Auto-Suggestions Plugin
  become: true
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
  tags:
    - install
    - zsh

- name: Install ZSH-Syntax-Highlighting Plugin
  become: true
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git'
    dest: "~/.oh-my-zsh/plugins/zsh-syntax-highlighting"
  tags:
    - install
    - zsh

# - name: Delete Original .zshrc File
#   become: true
#   command: rm "{{ lookup('env', 'Home') }}".zshrc
#   tags:
#     - install
#     - zsh

- name: Link Own .zshrc File
  become: true
  command: ln -s "{{ lookup('env', 'HOME') }}/dotfiles/zsh/.zshrc-deb" "{{ lookup('env', 'HOME') }}/.zshrc"
  tags:
    - install
    - zsh




