- name: Add PHP Repository
  become: true
  apt_repository: repo="ppa:ondrej/php" state=present
  tags:
    - install
    - languages
    - php

- name: Update Package Cache
  become: true
  apt: name=php8.3 state=present
  tags:
    - install
    - languages
    - php

- name: Install PHP 8.3
  become: true
  apt: name=php8.3 state=present
  tags:
    - install
    - languages
    - php

- name: Install PHP 8.3 Package Set
  become: true
  apt:
    name: ["php8.3-mbstring", "php8.3-common", "php8.3-cli", "php8.3-fpm", "php8.3-curl", "php8.3-bz2", "php8.3-intl"]
  tags:
    - install
    - languages
    - php

- name: Download Composer
  become: true
  command: sh -c "curl -sS https://getcomposer.org/installer -o composer-setup.php"
  tags:
    - install
    - languages
    - php

- name: Install Composer
  become: true
  command: php composer-setup.php --install-dir=/usr/local/bin --filename=composer
  tags:
    - install
    - languages
    - php
