- name: Download Rust Installer
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: '0755'
    force: 'yes'
  tags:
    - install
    - languages
    - rust

- name: Install Rust & Cargo
  shell: /tmp/sh.rustup.rs -y
  tags:
    - install
    - languages
    - rust

- name: Add Cargo Environment to ~/.bashrc
  ansible.builtin.lineinfile:
    dest: ~/.bashrc
    line: '[ -f ~/.cargo/env ] && source $HOME/.cargo/env'
    insertafter: EOF
  tags:
    - install
    - languages
    - rust

- name: Source .bashrc File
  ansible.builtin.shell: source ~/.bashrc
  args:
    executable: /bin/bash
  environment:
    HOME: "{{ ansible_env.HOME }}"
  tags:
    - install
    - languages
    - rust
