- name: Install typescript
  become: true
  npm:
    name: "{{ item }}"
    global: yes
  with_items:
    - eslint
    - typescript-language-server
    - typescript
    - ts-node
  tags:
    - install
    - languages
    - typescript

